#!/usr/bin/env python3
r"""
Train in-situ PyTorch multitarget NN using an optional predicted phase-transition feature.

Default phase use:
    group-level extra feature = pred_phase_transition_K only.

For physics-filtered training, pass the filtered CSV generated by:
    add_phase_transition_predictions_and_filter_property_dataset.py

In-situ PyTorch multi-task model for IL density, Cp, and viscosity.

This script DOES NOT first create per-group fitted viscosity/density parameters.
Instead, the neural network predicts group-level curve coefficients from
RDKit/composition descriptors, reconstructs properties at each pointwise
measurement temperature inside the forward pass, and trains directly against
pointwise data.

Architecture:
    group descriptors -> shared MLP ->
        density head: v0, v1 for linear specific volume
            1/rho(T) = v0 + v1*(T - Tref)

        viscosity head: inverse-temperature Taylor/VFT-polynomial coefficients
            log10(eta) = A + b1*(Tref/T) + ... + bd*(Tref/T)^d

        Cp residual head:
            Cp_prior = Ridge([1/rho_pred]) using the same Cp prior form as before
            Cp = Cp_prior + residual_NN(descriptors, T, rho_pred)

No Morgan fingerprints are used. N_BITS is fixed internally to 0.

Example:
    python .\train_insitu_multitask_nn_no_morgan.py --input .\strict_same_condition_training_all.csv --output_dir .\insitu_nn_no_morgan_results --degree 4 --epochs 1000 --patience 100
"""

from __future__ import annotations

import argparse
import json
import math
import random
import re
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

try:
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    from torch.utils.data import DataLoader, Dataset
except Exception as exc:  # pragma: no cover
    raise SystemExit(
        "PyTorch is required. Install with one of these commands, for example:\n"
        "    conda install pytorch cpuonly -c pytorch\n"
        "or use your existing ilthermo environment if torch is already installed.\n"
        f"Original import error: {exc}"
    )

try:
    from rdkit import Chem
    from rdkit.Chem import AllChem, Crippen, Descriptors, Lipinski, rdMolDescriptors
except Exception as exc:  # pragma: no cover
    raise SystemExit(
        "RDKit is required. Install with:\n"
        "    conda install -c conda-forge rdkit\n"
        f"Original import error: {exc}"
    )

warnings.filterwarnings("ignore", category=UserWarning)

# Hard-disable Morgan fingerprints. Do not change this for the no-Morgan workflow.
N_BITS = 0

ELEMENTS = [
    "B", "C", "N", "O", "F", "P", "S", "Cl", "Br", "I", "Si", "Li", "Na", "K"
]


def norm_text(x: object) -> str:
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return ""
    return str(x).strip()


def first_existing(df: pd.DataFrame, names: Iterable[str]) -> Optional[str]:
    lower_map = {c.lower(): c for c in df.columns}
    for name in names:
        if name in df.columns:
            return name
        if name.lower() in lower_map:
            return lower_map[name.lower()]
    return None


def to_numeric_series(df: pd.DataFrame, col: str, default: float = np.nan) -> pd.Series:
    if col in df.columns:
        return pd.to_numeric(df[col], errors="coerce")
    return pd.Series(default, index=df.index, dtype=float)


def safe_div(a: np.ndarray | pd.Series | float, b: np.ndarray | pd.Series | float) -> np.ndarray:
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    out = np.full(np.broadcast_shapes(a.shape, b.shape), np.nan, dtype=float)
    aa = np.broadcast_to(a, out.shape)
    bb = np.broadcast_to(b, out.shape)
    mask = np.isfinite(aa) & np.isfinite(bb) & (np.abs(bb) > 1e-12)
    out[mask] = aa[mask] / bb[mask]
    return out


def mol_from_smiles(smiles: object) -> Optional[Chem.Mol]:
    s = norm_text(smiles)
    if not s:
        return None
    try:
        mol = Chem.MolFromSmiles(s)
        return mol
    except Exception:
        return None


def formal_charge(mol: Optional[Chem.Mol]) -> float:
    if mol is None:
        return np.nan
    try:
        return float(sum(atom.GetFormalCharge() for atom in mol.GetAtoms()))
    except Exception:
        return np.nan


def atom_counts(mol: Optional[Chem.Mol]) -> Dict[str, float]:
    counts = {f"n_{el}": 0.0 for el in ELEMENTS}
    counts["n_H_total"] = 0.0
    counts["n_heavy_total"] = 0.0
    counts["n_halogen"] = 0.0
    counts["n_hetero_no_halogen"] = 0.0
    if mol is None:
        return {k: np.nan for k in counts}

    try:
        for atom in mol.GetAtoms():
            el = atom.GetSymbol()
            if el in ELEMENTS:
                counts[f"n_{el}"] += 1.0
            counts["n_H_total"] += float(atom.GetTotalNumHs())
            if el != "H":
                counts["n_heavy_total"] += 1.0
            if el in ["F", "Cl", "Br", "I"]:
                counts["n_halogen"] += 1.0
            if el not in ["C", "H", "F", "Cl", "Br", "I"]:
                counts["n_hetero_no_halogen"] += 1.0
    except Exception:
        return {k: np.nan for k in counts}
    return counts


# RDKit scalar descriptor section kept in the same style as the previous script.
def rdkit_scalar_descriptors(smiles: object) -> Dict[str, float]:
    mol = mol_from_smiles(smiles)
    keys = [
        "MolWt", 
        #"ExactMolWt", 
        "HeavyAtomMolWt", "HeavyAtomCount",
        # "NumValenceElectrons",
        "TPSA", "LabuteASA", 
        #"MolMR", 
        #"MolLogP", 
        "NumHAcceptors", "NumHDonors",
        "NumRotatableBonds", "RingCount", "NumAromaticRings", "NumAliphaticRings",
        "FractionCSP3", 
        #"BertzCT", "BalabanJ", 
        #"Chi0", "Chi1", "Chi0n", "Chi1n",
       # "Kappa1", "Kappa2", "Kappa3", "HallKierAlpha",
        # "formal_charge",
        #"abs_formal_charge",
    ]
    if mol is None:
        d = {k: np.nan for k in keys}
        d.update(atom_counts(None))
        return d

    def try_float(fn, default=np.nan):
        try:
            val = fn(mol)
            if val is None:
                return default
            return float(val)
        except Exception:
            return default

    chg = formal_charge(mol)
    d = {
        "MolWt": try_float(Descriptors.MolWt),
        #"ExactMolWt": try_float(Descriptors.ExactMolWt),
        "HeavyAtomMolWt": try_float(Descriptors.HeavyAtomMolWt),
        "HeavyAtomCount": try_float(Descriptors.HeavyAtomCount),
        #"NumValenceElectrons": try_float(Descriptors.NumValenceElectrons),
        "TPSA": try_float(rdMolDescriptors.CalcTPSA),
        "LabuteASA": try_float(rdMolDescriptors.CalcLabuteASA),
        #"MolMR": try_float(Crippen.MolMR),
        #"MolLogP": try_float(Crippen.MolLogP),
        "NumHAcceptors": try_float(Lipinski.NumHAcceptors),
        "NumHDonors": try_float(Lipinski.NumHDonors),
        "NumRotatableBonds": try_float(Lipinski.NumRotatableBonds),
        "RingCount": try_float(Lipinski.RingCount),
        "NumAromaticRings": try_float(Lipinski.NumAromaticRings),
        "NumAliphaticRings": try_float(Lipinski.NumAliphaticRings),
        "FractionCSP3": try_float(rdMolDescriptors.CalcFractionCSP3),
        #"BertzCT": try_float(Descriptors.BertzCT),
        #"BalabanJ": try_float(Descriptors.BalabanJ),
        #"Chi0": try_float(Descriptors.Chi0),
        #"Chi1": try_float(Descriptors.Chi1),
        #"Chi0n": try_float(Descriptors.Chi0n),
        #"Chi1n": try_float(Descriptors.Chi1n),
        #"Kappa1": try_float(Descriptors.Kappa1),
        #"Kappa2": try_float(Descriptors.Kappa2),
        #"Kappa3": try_float(Descriptors.Kappa3),
        #"HallKierAlpha": try_float(Descriptors.HallKierAlpha),
        #"formal_charge": chg,
        #"abs_formal_charge": abs(chg) if np.isfinite(chg) else np.nan,
    }
    d.update(atom_counts(mol))
    return d


def morgan_count_fp(smiles: object, n_bits: int = N_BITS, radius: int = 2) -> np.ndarray:
    # Morgan fingerprints are intentionally disabled in this workflow.
    if n_bits <= 0:
        return np.zeros(0, dtype=float)

    mol = mol_from_smiles(smiles)
    arr = np.zeros(n_bits, dtype=float)
    if mol is None:
        arr[:] = np.nan
        return arr
    try:
        fp = AllChem.GetHashedMorganFingerprint(mol, radius=radius, nBits=n_bits)
        for bit, val in fp.GetNonzeroElements().items():
            arr[int(bit) % n_bits] = float(val)
    except Exception:
        arr[:] = np.nan
    return arr


def split_dot_smiles(smiles: object) -> Tuple[str, str, str]:
    """Return (anion, cation, status). Only uses formal charge, no repair."""
    s = norm_text(smiles)
    if not s or "." not in s:
        return "", "", "no_dot_or_blank"
    frags = [f.strip() for f in s.split(".") if f.strip()]
    if len(frags) != 2:
        return "", "", "not_two_fragments"
    mols = [mol_from_smiles(f) for f in frags]
    if any(m is None for m in mols):
        return "", "", "parse_failed"
    charges = [formal_charge(m) for m in mols]
    if sorted(charges) != [-1.0, 1.0]:
        return "", "", f"bad_charges_{charges}"
    anion = frags[int(np.argmin(charges))]
    cation = frags[int(np.argmax(charges))]
    return anion, cation, "ok"


def get_smiles_columns(df: pd.DataFrame) -> Dict[str, Optional[str]]:
    return {
        "IL1_smiles": first_existing(df, ["IL1_smiles", "il1_smiles", "component_1_smiles", "component_1_SMILES"]),
        "IL1_anion_smiles": first_existing(df, ["IL1_anion_smiles", "il1_anion_smiles", "component_1_anion_smiles"]),
        "IL1_cation_smiles": first_existing(df, ["IL1_cation_smiles", "il1_cation_smiles", "component_1_cation_smiles"]),
        "IL2_smiles": first_existing(df, ["IL2_smiles", "il2_smiles", "component_2_smiles", "component_2_SMILES"]),
        "IL2_anion_smiles": first_existing(df, ["IL2_anion_smiles", "il2_anion_smiles", "component_2_anion_smiles"]),
        "IL2_cation_smiles": first_existing(df, ["IL2_cation_smiles", "il2_cation_smiles", "component_2_cation_smiles"]),
    }


def ensure_ion_smiles(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure IL1/IL2 whole/cation/anion SMILES columns exist in standardized names."""
    df = df.copy()
    cols = get_smiles_columns(df)

    for std, col in cols.items():
        if col is not None and col != std:
            df[std] = df[col]
        elif col is None and std not in df.columns:
            df[std] = ""

    for prefix in ["IL1", "IL2"]:
        whole = f"{prefix}_smiles"
        anion = f"{prefix}_anion_smiles"
        cation = f"{prefix}_cation_smiles"
        if whole not in df.columns:
            df[whole] = ""
        if anion not in df.columns:
            df[anion] = ""
        if cation not in df.columns:
            df[cation] = ""

        # Fill cation/anion from whole dot SMILES where missing.
        new_anions = []
        new_cations = []
        for old_a, old_c, smi in zip(df[anion], df[cation], df[whole]):
            a = norm_text(old_a)
            c = norm_text(old_c)
            if a and c:
                new_anions.append(a)
                new_cations.append(c)
            else:
                aa, cc, status = split_dot_smiles(smi)
                new_anions.append(a or aa)
                new_cations.append(c or cc)
        df[anion] = new_anions
        df[cation] = new_cations

    return df


def likely_binary_row(row: pd.Series) -> bool:
    x2 = row.get("x2", 0.0)
    il2 = norm_text(row.get("IL2_smiles", "")) or norm_text(row.get("IL2_cation_smiles", "")) or norm_text(row.get("IL2_anion_smiles", ""))
    try:
        return bool(np.isfinite(float(x2)) and float(x2) > 1e-8 and il2)
    except Exception:
        return bool(il2)


def descriptors_for_il(cation: object, anion: object, whole: object, n_bits: int = N_BITS) -> Tuple[Dict[str, float], np.ndarray]:
    cat = rdkit_scalar_descriptors(cation)
    an = rdkit_scalar_descriptors(anion)
    whole_desc = rdkit_scalar_descriptors(whole if norm_text(whole) else f"{norm_text(anion)}.{norm_text(cation)}")

    out: Dict[str, float] = {}
    for k, v in cat.items():
        out[f"cat_{k}"] = v
    for k, v in an.items():
        out[f"an_{k}"] = v
    for k, v in whole_desc.items():
        out[f"whole_{k}"] = v

    cat_fp = morgan_count_fp(cation, n_bits=n_bits)
    an_fp = morgan_count_fp(anion, n_bits=n_bits)
    fp = np.concatenate([cat_fp, an_fp])
    return out, fp


def il_key(row: pd.Series, prefix: str) -> str:
    whole = norm_text(row.get(f"{prefix}_smiles", ""))
    if whole:
        return whole
    an = norm_text(row.get(f"{prefix}_anion_smiles", ""))
    cat = norm_text(row.get(f"{prefix}_cation_smiles", ""))
    return f"{an}.{cat}" if an or cat else ""


def canonical_group(row: pd.Series, x_round: int = 6) -> Dict[str, object]:
    """Canonicalize pure/binary groups including composition.

    For binaries, the two ILs are sorted by their SMILES key, and x_canonical
    is always the mole fraction of the first sorted IL. Therefore label-swapped
    rows map to the same group.
    """
    il1_key = il_key(row, "IL1")
    il2_key = il_key(row, "IL2")
    x1 = row.get("x1", 1.0)
    x2 = row.get("x2", 0.0)
    try:
        x1f = float(x1) if pd.notna(x1) else 1.0
    except Exception:
        x1f = 1.0
    try:
        x2f = float(x2) if pd.notna(x2) else 0.0
    except Exception:
        x2f = 0.0

    # Treat x=0 or x=1 endpoints as pure if one component is absent/negligible.
    if (not il2_key) or x2f <= 1e-8:
        return {
            "group_id": f"pure::{il1_key}",
            "is_binary_canonical": 0,
            "IL_A_key": il1_key,
            "IL_B_key": "",
            "x_A": 1.0,
            "x_B": 0.0,
            "source_order_swapped": 0,
        }
    if x1f <= 1e-8:
        return {
            "group_id": f"pure::{il2_key}",
            "is_binary_canonical": 0,
            "IL_A_key": il2_key,
            "IL_B_key": "",
            "x_A": 1.0,
            "x_B": 0.0,
            "source_order_swapped": 0,
        }

    if il1_key <= il2_key:
        A_key, B_key = il1_key, il2_key
        xA, xB = x1f, x2f
        swapped = 0
    else:
        A_key, B_key = il2_key, il1_key
        xA, xB = x2f, x1f
        swapped = 1

    xr = round(float(xA), x_round)
    group_id = f"binary::{A_key}||{B_key}::xA={xr:.{x_round}f}"
    return {
        "group_id": group_id,
        "is_binary_canonical": 1,
        "IL_A_key": A_key,
        "IL_B_key": B_key,
        "x_A": float(xA),
        "x_B": float(xB),
        "source_order_swapped": swapped,
    }


def build_group_feature_table(point_df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Return (point_df_with_group_meta, group_feature_df)."""
    df = ensure_ion_smiles(point_df)
    meta = df.apply(canonical_group, axis=1, result_type="expand")
    df = pd.concat([df.reset_index(drop=True), meta.reset_index(drop=True)], axis=1)

    # Build a lookup from whole IL key to cation/anion/whole SMILES. First nonempty wins.
    il_lookup: Dict[str, Dict[str, str]] = {}
    for _, row in df.iterrows():
        for prefix in ["IL1", "IL2"]:
            key = il_key(row, prefix)
            if not key:
                continue
            if key not in il_lookup:
                il_lookup[key] = {
                    "whole": norm_text(row.get(f"{prefix}_smiles", "")),
                    "anion": norm_text(row.get(f"{prefix}_anion_smiles", "")),
                    "cation": norm_text(row.get(f"{prefix}_cation_smiles", "")),
                }

    cache_desc: Dict[str, Dict[str, float]] = {}

    def desc_for_key(key: str) -> Dict[str, float]:
        if not key:
            return {}
        if key not in cache_desc:
            rec = il_lookup.get(key, {})
            d, _fp = descriptors_for_il(rec.get("cation", ""), rec.get("anion", ""), rec.get("whole", key), n_bits=N_BITS)
            cache_desc[key] = d
        return cache_desc[key]

    group_rows: List[Dict[str, float | str | int]] = []
    for gid, g in df.groupby("group_id", sort=False):
        row0 = g.iloc[0]
        A_key = norm_text(row0["IL_A_key"])
        B_key = norm_text(row0["IL_B_key"])
        xA = float(row0["x_A"])
        xB = float(row0["x_B"])
        is_binary = int(row0["is_binary_canonical"])

        dA = desc_for_key(A_key)
        dB = desc_for_key(B_key) if B_key else {k: 0.0 for k in dA.keys()}

        out: Dict[str, float | str | int] = {
            "group_id": gid,
            "is_binary_canonical": is_binary,
            "IL_A_key": A_key,
            "IL_B_key": B_key,
            "x_A": xA,
            "x_B": xB,
            "x_A_x_B": xA * xB,
        }
        keys = sorted(set(dA.keys()).union(dB.keys()))
        for k in keys:
            vA = float(dA.get(k, np.nan))
            vB = float(dB.get(k, 0.0 if not B_key else np.nan))
            if not np.isfinite(vB) and xB == 0:
                vB = 0.0
            out[f"IL_A_{k}"] = vA
            out[f"IL_B_{k}"] = vB
            out[f"mix_{k}"] = xA * vA + xB * vB if np.isfinite(vA) and np.isfinite(vB) else np.nan
            out[f"diff_{k}"] = abs(vA - vB) if np.isfinite(vA) and np.isfinite(vB) else np.nan
            out[f"interaction_{k}"] = xA * xB * abs(vA - vB) if np.isfinite(vA) and np.isfinite(vB) else np.nan
        group_rows.append(out)

    group_df = pd.DataFrame(group_rows)
    return df, group_df


def fit_cp_prior(train_df: pd.DataFrame) -> Tuple[Pipeline, Dict[str, float]]:
    cp = pd.to_numeric(train_df.get("cp_JkgK"), errors="coerce").to_numpy(float)
    rho = pd.to_numeric(train_df.get("density_kg_m3"), errors="coerce").to_numpy(float)
    mask = np.isfinite(cp) & np.isfinite(rho) & (rho > 0)
    if mask.sum() < 5:
        raise ValueError("Not enough training rows with both Cp and density to fit Cp prior.")
    X = pd.DataFrame({"inv_density": 1.0 / rho[mask]})
    y = cp[mask]
    pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("ridge", Ridge(alpha=1.0)),
    ])
    pipe.fit(X, y)

    scaler = pipe.named_steps["scaler"]
    ridge = pipe.named_steps["ridge"]
    params = {
        "ridge_intercept": float(ridge.intercept_),
        "ridge_coef_scaled_inv_density": float(ridge.coef_[0]),
        "scaler_mean_inv_density": float(scaler.mean_[0]),
        "scaler_scale_inv_density": float(scaler.scale_[0]) if float(scaler.scale_[0]) != 0 else 1.0,
        "n_cp_prior_train": int(mask.sum()),
    }
    return pipe, params


def cp_prior_from_params(inv_density: torch.Tensor, params: Dict[str, float]) -> torch.Tensor:
    z = (inv_density - params["scaler_mean_inv_density"]) / params["scaler_scale_inv_density"]
    return params["ridge_intercept"] + params["ridge_coef_scaled_inv_density"] * z


@dataclass
class Scaling:
    rho_std: float
    cp_mean: float
    cp_std: float
    logeta_mean: float
    logeta_std: float
    invrho_scale: float
    tref: float


class ILPointDataset(Dataset):
    def __init__(self, row_df: pd.DataFrame, group_to_idx: Dict[str, int]):
        self.group_idx = np.array([group_to_idx[g] for g in row_df["group_id"].values], dtype=np.int64)
        self.T = pd.to_numeric(row_df["temperature_K"], errors="coerce").to_numpy(np.float32)
        self.rho = pd.to_numeric(row_df.get("density_kg_m3"), errors="coerce").to_numpy(np.float32)
        self.cp = pd.to_numeric(row_df.get("cp_JkgK"), errors="coerce").to_numpy(np.float32)
        if "log10_viscosity_mPa_s" in row_df.columns:
            self.logeta = pd.to_numeric(row_df["log10_viscosity_mPa_s"], errors="coerce").to_numpy(np.float32)
        else:
            eta = pd.to_numeric(row_df.get("viscosity_mPa_s"), errors="coerce").to_numpy(float)
            self.logeta = np.where(np.isfinite(eta) & (eta > 0), np.log10(eta), np.nan).astype(np.float32)

        self.rho_mask = np.isfinite(self.rho).astype(np.float32)
        self.cp_mask = np.isfinite(self.cp).astype(np.float32)
        self.eta_mask = np.isfinite(self.logeta).astype(np.float32)

        # Replace NaNs with zeros so tensors are finite; masks control losses.
        self.rho = np.where(np.isfinite(self.rho), self.rho, 0.0).astype(np.float32)
        self.cp = np.where(np.isfinite(self.cp), self.cp, 0.0).astype(np.float32)
        self.logeta = np.where(np.isfinite(self.logeta), self.logeta, 0.0).astype(np.float32)

    def __len__(self) -> int:
        return len(self.T)

    def __getitem__(self, idx: int):
        return {
            "group_idx": torch.tensor(self.group_idx[idx], dtype=torch.long),
            "T": torch.tensor(self.T[idx], dtype=torch.float32),
            "rho": torch.tensor(self.rho[idx], dtype=torch.float32),
            "cp": torch.tensor(self.cp[idx], dtype=torch.float32),
            "logeta": torch.tensor(self.logeta[idx], dtype=torch.float32),
            "rho_mask": torch.tensor(self.rho_mask[idx], dtype=torch.float32),
            "cp_mask": torch.tensor(self.cp_mask[idx], dtype=torch.float32),
            "eta_mask": torch.tensor(self.eta_mask[idx], dtype=torch.float32),
        }


class InSituILModel(nn.Module):
    def __init__(self, n_features: int, degree: int, hidden: List[int], dropout: float, scaling: Scaling, cp_prior_params: Dict[str, float]):
        super().__init__()
        self.degree = degree
        self.scaling = scaling
        self.cp_prior_params = cp_prior_params

        layers: List[nn.Module] = []
        prev = n_features
        for h in hidden:
            layers.append(nn.Linear(prev, h))
            layers.append(nn.ReLU())
            if dropout > 0:
                layers.append(nn.Dropout(dropout))
            prev = h
        self.shared = nn.Sequential(*layers)

        self.density_head = nn.Linear(prev, 2)          # scaled v0, scaled v1
        self.eta_head = nn.Linear(prev, degree + 1)     # scaled A, b1..bd
        self.cp_head = nn.Sequential(
            nn.Linear(prev + degree + 4, max(32, hidden[-1] // 2 if hidden else 64)),
            nn.ReLU(),
            nn.Dropout(dropout) if dropout > 0 else nn.Identity(),
            nn.Linear(max(32, hidden[-1] // 2 if hidden else 64), 1),
        )

        self._init_heads()

    def _init_heads(self) -> None:
        # Start density near invrho_scale * 1.0 with weak T-dependence.
        nn.init.zeros_(self.density_head.weight)
        nn.init.zeros_(self.density_head.bias)
        with torch.no_grad():
            self.density_head.bias[0] = 1.0  # v0_scaled
            self.density_head.bias[1] = 0.0  # v1_scaled per 100 K

        nn.init.zeros_(self.eta_head.weight)
        nn.init.zeros_(self.eta_head.bias)
        nn.init.zeros_(self.cp_head[-1].weight)
        nn.init.zeros_(self.cp_head[-1].bias)

    def forward(self, X_group: torch.Tensor, group_idx: torch.Tensor, T: torch.Tensor) -> Dict[str, torch.Tensor]:
        h = self.shared(X_group[group_idx])
        dcoef = self.density_head(h)
        ecoef = self.eta_head(h)

        Tref = self.scaling.tref
        dT_scaled = (T - Tref) / 100.0
        theta = Tref / torch.clamp(T, min=1.0)
        theta_powers = torch.stack([theta ** k for k in range(1, self.degree + 1)], dim=1)

        # Linear specific volume in scaled form:
        # invrho = invrho_scale * (v0_scaled + v1_scaled * ((T-Tref)/100)).
        v_scaled = dcoef[:, 0] + dcoef[:, 1] * dT_scaled
        v_scaled_clamped = torch.clamp(v_scaled, min=0.2, max=3.0)
        invrho_pred = self.scaling.invrho_scale * v_scaled_clamped
        rho_pred = 1.0 / torch.clamp(invrho_pred, min=1e-8)

        # Dimensionless inverse-temperature polynomial. The NN coefficients are
        # scaled by logeta_std and shifted by logeta_mean for numerical stability.
        eta_scaled = ecoef[:, 0] + torch.sum(ecoef[:, 1:] * theta_powers, dim=1)
        logeta_pred = self.scaling.logeta_mean + self.scaling.logeta_std * eta_scaled

        rho_scaled = rho_pred / 1000.0
        invrho_scaled = invrho_pred / self.scaling.invrho_scale
        T_scaled = (T - Tref) / 100.0
        cp_in = torch.cat([
            h,
            T_scaled[:, None],
            theta[:, None],
            theta_powers,
            rho_scaled[:, None],
            invrho_scaled[:, None],
        ], dim=1)
        # No density-coupled Cp prior:
        # Cp is predicted directly from the shared representation, temperature,
        # and density-derived features, scaled around the training-set Cp mean.
        cp_scaled = self.cp_head(cp_in).squeeze(1)
        cp_pred = self.scaling.cp_mean + self.scaling.cp_std * cp_scaled

        return {
            "rho_pred": rho_pred,
            "invrho_pred": invrho_pred,
            "logeta_pred": logeta_pred,
            "cp_pred": cp_pred,
            "density_coeff_scaled": dcoef,
            "eta_coeff_scaled": ecoef,
        }



class CleanPhysicsLossWrapper(nn.Module):
    """
    Clean explicit physics-loss version.

    base_model gives structured predictions:
        rho_struct(T)
        logeta_struct(T)
        cp_struct(T)

    auxiliary free/direct heads give:
        rho_free(T)
        logeta_free(T)

    Training loss uses:
        data loss:    free rho/logeta against data
        physics loss: free rho/logeta against structured rho/logeta

    Cp is trained without the density-coupled Cp prior: Cp_pred = Cp_mean + Cp_std*NN_output.
    Existing screening scripts remain compatible because the saved
    insitu_multitask_nn_no_morgan.pt stores only base_model.
    """
    def __init__(
        self,
        n_features: int,
        degree: int,
        hidden: List[int],
        dropout: float,
        scaling: Scaling,
        cp_prior_params: Dict[str, float],
        rho_mean: float,
    ):
        super().__init__()
        self.base_model = InSituILModel(
            n_features=n_features,
            degree=degree,
            hidden=hidden,
            dropout=dropout,
            scaling=scaling,
            cp_prior_params=cp_prior_params,
        )
        self.scaling = scaling
        self.rho_mean = float(rho_mean)
        last_hidden = hidden[-1] if hidden else n_features

        direct_in_dim = last_hidden + degree + 3
        mid = max(32, last_hidden // 2 if hidden else 64)

        self.rho_free_head = nn.Sequential(
            nn.Linear(direct_in_dim, mid),
            nn.ReLU(),
            nn.Dropout(dropout) if dropout > 0 else nn.Identity(),
            nn.Linear(mid, 1),
        )
        self.logeta_free_head = nn.Sequential(
            nn.Linear(direct_in_dim, mid),
            nn.ReLU(),
            nn.Dropout(dropout) if dropout > 0 else nn.Identity(),
            nn.Linear(mid, 1),
        )
        self._init_free_heads()

    def _init_free_heads(self) -> None:
        for head in [self.rho_free_head, self.logeta_free_head]:
            nn.init.zeros_(head[-1].weight)
            nn.init.zeros_(head[-1].bias)

    def forward(self, X_group: torch.Tensor, group_idx: torch.Tensor, T: torch.Tensor) -> Dict[str, torch.Tensor]:
        out = self.base_model(X_group, group_idx, T)
        h = self.base_model.shared(X_group[group_idx])

        Tref = self.scaling.tref
        T_scaled = (T - Tref) / 100.0
        theta = Tref / torch.clamp(T, min=1.0)
        theta_powers = torch.stack([theta ** k for k in range(1, self.base_model.degree + 1)], dim=1)

        direct_in = torch.cat([
            h,
            T_scaled[:, None],
            theta[:, None],
            theta_powers,
            out["rho_pred"][:, None] / 1000.0,
        ], dim=1)

        rho_free_scaled = self.rho_free_head(direct_in).squeeze(1)
        logeta_free_scaled = self.logeta_free_head(direct_in).squeeze(1)

        out["rho_free_pred"] = self.rho_mean + self.scaling.rho_std * rho_free_scaled
        out["logeta_free_pred"] = self.scaling.logeta_mean + self.scaling.logeta_std * logeta_free_scaled
        return out


def masked_mse(pred: torch.Tensor, true: torch.Tensor, mask: torch.Tensor, scale: float) -> torch.Tensor:
    m = mask > 0.5
    if torch.sum(m) == 0:
        return pred.sum() * 0.0
    err = (pred[m] - true[m]) / scale
    return torch.mean(err * err)


def collect_predictions(model: InSituILModel, X_group_tensor: torch.Tensor, loader: DataLoader, device: torch.device) -> pd.DataFrame:
    model.eval()
    rows = []
    with torch.no_grad():
        for batch in loader:
            group_idx = batch["group_idx"].to(device)
            T = batch["T"].to(device)
            out = model(X_group_tensor, group_idx, T)
            n = len(T)
            for i in range(n):
                rows.append({
                    "group_idx_internal": int(group_idx[i].cpu().item()),
                    "temperature_K": float(T[i].cpu().item()),
                    "density_true_kg_m3": float(batch["rho"][i].item()) if batch["rho_mask"][i].item() > 0.5 else np.nan,
                    "cp_true_JkgK": float(batch["cp"][i].item()) if batch["cp_mask"][i].item() > 0.5 else np.nan,
                    "log10_viscosity_true_mPa_s": float(batch["logeta"][i].item()) if batch["eta_mask"][i].item() > 0.5 else np.nan,
                    "density_pred_kg_m3": float(out["rho_pred"][i].cpu().item()),
                    "cp_pred_JkgK": float(out["cp_pred"][i].cpu().item()),
                    "log10_viscosity_pred_mPa_s": float(out["logeta_pred"][i].cpu().item()),
                    "density_free_pred_kg_m3": float(out["rho_free_pred"][i].cpu().item()) if "rho_free_pred" in out else np.nan,
                    "log10_viscosity_free_pred_mPa_s": float(out["logeta_free_pred"][i].cpu().item()) if "logeta_free_pred" in out else np.nan,
                })
    return pd.DataFrame(rows)


def metric_rows(pred_df: pd.DataFrame, split: str) -> List[Dict[str, float | str | int]]:
    specs = [
        ("density_kg_m3", "density_true_kg_m3", "density_pred_kg_m3", False),
        ("cp_JkgK", "cp_true_JkgK", "cp_pred_JkgK", False),
        ("log10_viscosity_mPa_s", "log10_viscosity_true_mPa_s", "log10_viscosity_pred_mPa_s", True),
    ]
    rows = []
    for target, true_col, pred_col, is_logeta in specs:
        yt = pd.to_numeric(pred_df[true_col], errors="coerce").to_numpy(float)
        yp = pd.to_numeric(pred_df[pred_col], errors="coerce").to_numpy(float)
        m = np.isfinite(yt) & np.isfinite(yp)
        if m.sum() == 0:
            continue
        rmse = math.sqrt(mean_squared_error(yt[m], yp[m]))
        mae = mean_absolute_error(yt[m], yp[m])
        rows.append({
            "split": split,
            "target": target,
            "n": int(m.sum()),
            "r2": float(r2_score(yt[m], yp[m])) if m.sum() > 1 else np.nan,
            "mae": float(mae),
            "rmse": float(rmse),
            "factor_error_rmse": float(10 ** rmse) if is_logeta else np.nan,
        })
    return rows


def parse_hidden(s: str) -> List[int]:
    return [int(x.strip()) for x in s.split(",") if x.strip()]


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="Pointwise cleaned pure/binary IL CSV.")
    ap.add_argument("--output_dir", default="insitu_nn_no_morgan_results")
    ap.add_argument("--degree", type=int, default=4, help="Inverse-temperature polynomial degree for viscosity.")
    ap.add_argument("--epochs", type=int, default=1000)
    ap.add_argument("--patience", type=int, default=100)
    ap.add_argument("--batch_size", type=int, default=256)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--weight_decay", type=float, default=1e-4)
    ap.add_argument("--hidden", default="256,128")
    ap.add_argument("--dropout", type=float, default=0.05)
    ap.add_argument("--test_size", type=float, default=0.25)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--tref", type=float, default=298.15)
    ap.add_argument("--density_weight", type=float, default=1.0)
    ap.add_argument("--cp_weight", type=float, default=1.0)
    ap.add_argument("--viscosity_weight", type=float, default=1.0)

    # Clean explicit physics-consistency loss:
    # data loss uses free/direct rho and logeta predictions;
    # physics loss aligns free/direct predictions with structured heads.
    ap.add_argument("--rho_physics_weight", type=float, default=1.0)
    ap.add_argument("--eta_physics_weight", type=float, default=1.0)

    # Cp approximate temperature-invariance physics loss:
    # penalizes Cp(T) - Cp(Tref) for the same IL/group.
    ap.add_argument("--cp_const_weight", type=float, default=0.2)

    ap.add_argument("--device", default="auto", choices=["auto", "cpu", "cuda"])
    ap.add_argument("--num_threads", type=int, default=1, help="CPU threads for PyTorch. Use 1 on Windows if CPU training hangs or is slow.")
    ap.add_argument("--extra_feature_cols", default="pred_phase_transition_K",
                    help="Comma-separated numeric group-level columns from the input CSV to aggregate by group and append to the NN descriptor matrix. Default uses only pred_phase_transition_K. Use empty string to disable.")
    ap.add_argument("--extra_feature_prefixes", default="",
                    help="Comma-separated column prefixes to auto-include as extra group-level features. Default is empty to avoid accidentally aggregating pointwise phase-filter diagnostics such as T_minus_pred_phase_K.")
    args = ap.parse_args()

    if args.degree < 1:
        raise ValueError("--degree must be >= 1")

    if args.num_threads and args.num_threads > 0:
        torch.set_num_threads(args.num_threads)
    set_seed(args.seed)
    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if (args.device == "auto" and torch.cuda.is_available()) or args.device == "cuda" else "cpu")
    print(f"Using device: {device}")
    print(f"PyTorch CPU threads: {torch.get_num_threads()}")
    print("Morgan fingerprints: disabled; N_BITS=0")
    print("Clean physics-loss training: free/direct rho and viscosity fit data; structured heads enter through consistency loss.")
    print("Cp physics loss enabled: Cp(T) is regularized toward Cp(Tref); density-coupled Cp prior is disabled.")

    df = pd.read_csv(args.input)
    print(f"Input rows: {len(df)}")
    df = ensure_ion_smiles(df)
    if "log10_viscosity_mPa_s" not in df.columns and "viscosity_mPa_s" in df.columns:
        eta = pd.to_numeric(df["viscosity_mPa_s"], errors="coerce")
        df["log10_viscosity_mPa_s"] = np.where(eta > 0, np.log10(eta), np.nan)

    point_df, group_df_raw = build_group_feature_table(df)
    print(f"Canonical groups: {point_df['group_id'].nunique()}")

    # Optional extra group-level features, e.g. phase-transition predictions generated
    # by add_phase_transition_predictions_to_property_dataset.py. These features are
    # aggregated by canonical group_id and appended to the same group descriptor table
    # used by the in-situ PyTorch model. Pointwise targets remain density/Cp/log-viscosity.
    explicit_extra_cols = [c.strip() for c in str(args.extra_feature_cols).split(",") if c.strip()]
    extra_prefixes = [p.strip() for p in str(args.extra_feature_prefixes).split(",") if p.strip()]
    auto_extra_cols = []
    for c in point_df.columns:
        if c in {"group_id", "temperature_K", "density_kg_m3", "cp_JkgK", "viscosity_mPa_s", "log10_viscosity_mPa_s"}:
            continue
        if any(c.startswith(p) for p in extra_prefixes):
            auto_extra_cols.append(c)
    extra_cols = []
    for c in explicit_extra_cols + auto_extra_cols:
        if c in point_df.columns and c not in extra_cols:
            extra_cols.append(c)
    if extra_cols:
        extra_num = point_df[["group_id"] + extra_cols].copy()
        for c in extra_cols:
            extra_num[c] = pd.to_numeric(extra_num[c], errors="coerce")
        extra_group = extra_num.groupby("group_id", as_index=False).median(numeric_only=True)
        rename_map = {c: f"extra_{c}" for c in extra_cols}
        extra_group = extra_group.rename(columns=rename_map)
        group_df_raw = group_df_raw.merge(extra_group, on="group_id", how="left")
        print(f"Extra group-level features added: {len(extra_cols)} -> {', '.join(extra_cols)}")
    else:
        print("Extra group-level features added: 0")

    # Group split. All pointwise rows from a group go either train or test.
    unique_groups = pd.Series(point_df["group_id"].unique())
    dummy_X = np.arange(len(unique_groups)).reshape(-1, 1)
    splitter = GroupShuffleSplit(n_splits=1, test_size=args.test_size, random_state=args.seed)
    train_g_idx, test_g_idx = next(splitter.split(dummy_X, groups=unique_groups.values))
    train_groups = set(unique_groups.iloc[train_g_idx].values)
    test_groups = set(unique_groups.iloc[test_g_idx].values)

    train_rows = point_df[point_df["group_id"].isin(train_groups)].copy()
    test_rows = point_df[point_df["group_id"].isin(test_groups)].copy()
    print(f"Train groups: {len(train_groups)} | Test groups: {len(test_groups)}")
    print(f"Train rows: {len(train_rows)} | Test rows: {len(test_rows)}")

    # Build group feature matrix in the same order for all groups, then fit imputer/scaler on train groups only.
    group_df = group_df_raw.copy()
    group_ids_order = group_df["group_id"].tolist()
    group_to_idx = {g: i for i, g in enumerate(group_ids_order)}
    train_group_mask = group_df["group_id"].isin(train_groups).to_numpy()

    non_feature_cols = {"group_id", "IL_A_key", "IL_B_key"}
    feature_cols = [c for c in group_df.columns if c not in non_feature_cols]
    X_raw = group_df[feature_cols].apply(pd.to_numeric, errors="coerce")

    # Remove all-missing and constant columns based on training groups only.
    keep_cols = []
    for c in X_raw.columns:
        s = X_raw.loc[train_group_mask, c]
        if s.notna().sum() == 0:
            continue
        if s.dropna().nunique() <= 1:
            continue
        keep_cols.append(c)
    X_raw = X_raw[keep_cols]

    imputer = SimpleImputer(strategy="median")
    scaler = StandardScaler()
    X_train_imp = imputer.fit_transform(X_raw.loc[train_group_mask])
    scaler.fit(X_train_imp)
    X_all = scaler.transform(imputer.transform(X_raw)).astype(np.float32)
    print(f"Group descriptor features used: {X_all.shape[1]}")

    # Scaling constants from training rows.
    # Cp prior is intentionally dropped in this version.
    rho_train = pd.to_numeric(train_rows.get("density_kg_m3"), errors="coerce").to_numpy(float)
    cp_train = pd.to_numeric(train_rows.get("cp_JkgK"), errors="coerce").to_numpy(float)
    logeta_train = pd.to_numeric(train_rows.get("log10_viscosity_mPa_s"), errors="coerce").to_numpy(float)

    rho_mean = float(np.nanmean(rho_train)) if np.isfinite(np.nanmean(rho_train)) else 1000.0
    rho_std = float(np.nanstd(rho_train)) if np.isfinite(np.nanstd(rho_train)) and np.nanstd(rho_train) > 0 else 100.0
    cp_mean = float(np.nanmean(cp_train)) if np.isfinite(np.nanmean(cp_train)) else 1500.0
    cp_std = float(np.nanstd(cp_train)) if np.isfinite(np.nanstd(cp_train)) and np.nanstd(cp_train) > 0 else 200.0
    logeta_mean = float(np.nanmean(logeta_train)) if np.isfinite(np.nanmean(logeta_train)) else 0.0
    logeta_std = float(np.nanstd(logeta_train)) if np.isfinite(np.nanstd(logeta_train)) and np.nanstd(logeta_train) > 0 else 1.0
    invrho_train = 1.0 / rho_train[np.isfinite(rho_train) & (rho_train > 0)]
    invrho_scale = float(np.nanmedian(invrho_train)) if len(invrho_train) else 1.0 / 1000.0

    # Compatibility metadata only. This is NOT a fitted density-Cp ridge prior.
    # If an older loader calls cp_prior_from_params, it returns the constant cp_mean.
    cp_prior_pipe = None
    cp_prior_params = {
        "ridge_intercept": cp_mean,
        "ridge_coef_scaled_inv_density": 0.0,
        "scaler_mean_inv_density": invrho_scale,
        "scaler_scale_inv_density": 1.0,
        "n_cp_prior_train": 0,
        "dropped_density_coupled_cp_prior": True,
        "note": "Cp prior disabled; constant cp_mean stored only for backward-compatible loading.",
    }
    print("Cp prior: disabled. Cp is trained as Cp_mean + Cp_std*NN_output, with optional Cp(T)-Cp(Tref) regularization.")

    scaling = Scaling(rho_std=rho_std, cp_mean=cp_mean, cp_std=cp_std, logeta_mean=logeta_mean, logeta_std=logeta_std, invrho_scale=invrho_scale, tref=args.tref)

    train_ds = ILPointDataset(train_rows, group_to_idx)
    test_ds = ILPointDataset(test_rows, group_to_idx)
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, drop_last=False)
    eval_train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=False, drop_last=False)
    test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False, drop_last=False)

    X_group_tensor = torch.tensor(X_all, dtype=torch.float32, device=device)
    model = CleanPhysicsLossWrapper(
        n_features=X_all.shape[1],
        degree=args.degree,
        hidden=parse_hidden(args.hidden),
        dropout=args.dropout,
        scaling=scaling,
        cp_prior_params=cp_prior_params,
        rho_mean=rho_mean,
    ).to(device)

    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    best_loss = float("inf")
    best_state = None
    bad_epochs = 0
    history = []

    for epoch in range(1, args.epochs + 1):
        model.train()
        train_loss_sum = 0.0
        nb = 0
        for batch in train_loader:
            group_idx = batch["group_idx"].to(device)
            T = batch["T"].to(device)
            rho = batch["rho"].to(device)
            cp = batch["cp"].to(device)
            logeta = batch["logeta"].to(device)
            rho_mask = batch["rho_mask"].to(device)
            cp_mask = batch["cp_mask"].to(device)
            eta_mask = batch["eta_mask"].to(device)

            out = model(X_group_tensor, group_idx, T)

            # Clean version:
            # data loss fits free/direct predictions to measured data.
            loss_rho_data = masked_mse(out["rho_free_pred"], rho, rho_mask, scaling.rho_std)
            loss_eta_data = masked_mse(out["logeta_free_pred"], logeta, eta_mask, scaling.logeta_std)

            # Cp keeps the original structured Cp prior/residual target.
            loss_cp = masked_mse(out["cp_pred"], cp, cp_mask, scaling.cp_std)

            # Cp approximate temperature-invariance physics term:
            # for the same IL/group, penalize deviation from Cp at Tref.
            Tref_batch = torch.full_like(T, float(args.tref))
            out_tref = model(X_group_tensor, group_idx, Tref_batch)
            loss_cp_const = masked_mse(out["cp_pred"], out_tref["cp_pred"], cp_mask, scaling.cp_std)

            # explicit physics-consistency terms:
            # free/direct predictions are regularized toward structured physical heads.
            # No detach: gradients train both branches toward consistency.
            loss_rho_phys = masked_mse(out["rho_free_pred"], out["rho_pred"], rho_mask, scaling.rho_std)
            loss_eta_phys = masked_mse(out["logeta_free_pred"], out["logeta_pred"], eta_mask, scaling.logeta_std)

            loss = (
                args.density_weight * loss_rho_data
                + args.cp_weight * loss_cp
                + args.viscosity_weight * loss_eta_data
                + args.rho_physics_weight * loss_rho_phys
                + args.eta_physics_weight * loss_eta_phys
                + args.cp_const_weight * loss_cp_const
            )

            opt.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            opt.step()
            train_loss_sum += float(loss.detach().cpu().item())
            nb += 1

        # Validate on held-out groups.
        model.eval()
        val_loss_sum = 0.0
        val_nb = 0
        with torch.no_grad():
            for batch in test_loader:
                group_idx = batch["group_idx"].to(device)
                T = batch["T"].to(device)
                rho = batch["rho"].to(device)
                cp = batch["cp"].to(device)
                logeta = batch["logeta"].to(device)
                rho_mask = batch["rho_mask"].to(device)
                cp_mask = batch["cp_mask"].to(device)
                eta_mask = batch["eta_mask"].to(device)
                out = model(X_group_tensor, group_idx, T)
                loss_rho_data = masked_mse(out["rho_free_pred"], rho, rho_mask, scaling.rho_std)
                loss_eta_data = masked_mse(out["logeta_free_pred"], logeta, eta_mask, scaling.logeta_std)
                loss_cp = masked_mse(out["cp_pred"], cp, cp_mask, scaling.cp_std)

                Tref_batch = torch.full_like(T, float(args.tref))
                out_tref = model(X_group_tensor, group_idx, Tref_batch)
                loss_cp_const = masked_mse(out["cp_pred"], out_tref["cp_pred"], cp_mask, scaling.cp_std)

                loss_rho_phys = masked_mse(out["rho_free_pred"], out["rho_pred"], rho_mask, scaling.rho_std)
                loss_eta_phys = masked_mse(out["logeta_free_pred"], out["logeta_pred"], eta_mask, scaling.logeta_std)

                loss = (
                    args.density_weight * loss_rho_data
                    + args.cp_weight * loss_cp
                    + args.viscosity_weight * loss_eta_data
                    + args.rho_physics_weight * loss_rho_phys
                    + args.eta_physics_weight * loss_eta_phys
                    + args.cp_const_weight * loss_cp_const
                )
                val_loss_sum += float(loss.detach().cpu().item())
                val_nb += 1

        train_loss = train_loss_sum / max(nb, 1)
        val_loss = val_loss_sum / max(val_nb, 1)
        history.append({"epoch": epoch, "train_loss": train_loss, "val_loss": val_loss})

        if epoch == 1 or epoch % 25 == 0:
            print(f"epoch {epoch:5d} | train_loss {train_loss:.5f} | val_loss {val_loss:.5f}")

        if val_loss < best_loss - 1e-6:
            best_loss = val_loss
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            bad_epochs = 0
        else:
            bad_epochs += 1
            if bad_epochs >= args.patience:
                print(f"Early stopping at epoch {epoch}; best val_loss={best_loss:.5f}")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    # Predictions and metrics.
    train_pred = collect_predictions(model, X_group_tensor, eval_train_loader, device)
    test_pred = collect_predictions(model, X_group_tensor, test_loader, device)

    # Restore group_id into prediction rows.
    idx_to_group = {i: g for g, i in group_to_idx.items()}
    for pdf in [train_pred, test_pred]:
        pdf["group_id"] = pdf["group_idx_internal"].map(idx_to_group)

    metrics = pd.DataFrame(metric_rows(train_pred, "train_group") + metric_rows(test_pred, "test_group"))
    print("\nMetrics:")
    print(metrics.to_string(index=False))

    # Export group coefficients in physical units.
    model.eval()
    with torch.no_grad():
        all_group_idx = torch.arange(len(group_ids_order), dtype=torch.long, device=device)
        # Use Tref only to obtain coefficient heads; T does not affect coefficients.
        T_dummy = torch.full((len(group_ids_order),), float(args.tref), dtype=torch.float32, device=device)
        out_all = model(X_group_tensor, all_group_idx, T_dummy)
        dcoef = out_all["density_coeff_scaled"].detach().cpu().numpy()
        ecoef = out_all["eta_coeff_scaled"].detach().cpu().numpy()

    coef_df = group_df[["group_id", "IL_A_key", "IL_B_key", "is_binary_canonical", "x_A", "x_B"]].copy()
    coef_df["v0_m3_per_kg_at_Tref"] = scaling.invrho_scale * dcoef[:, 0]
    coef_df["v1_m3_per_kg_K"] = scaling.invrho_scale * dcoef[:, 1] / 100.0
    coef_df["A_eta"] = scaling.logeta_mean + scaling.logeta_std * ecoef[:, 0]
    for k in range(1, args.degree + 1):
        coef_df[f"b{k}_eta_dimless"] = scaling.logeta_std * ecoef[:, k]

    # Save everything.
    train_pred.to_csv(outdir / "pointwise_predictions_train_group.csv", index=False)
    test_pred.to_csv(outdir / "pointwise_predictions_test_group.csv", index=False)
    metrics.to_csv(outdir / "metrics_group_split.csv", index=False)
    pd.DataFrame(history).to_csv(outdir / "training_history.csv", index=False)
    coef_df.to_csv(outdir / "predicted_group_curve_coefficients.csv", index=False)
    group_df.to_csv(outdir / "group_metadata_and_raw_features.csv", index=False)

    # Full checkpoint includes the auxiliary free/direct heads.
    torch.save({
        "model_state_dict": model.state_dict(),
        "degree": args.degree,
        "hidden": parse_hidden(args.hidden),
        "dropout": args.dropout,
        "feature_cols": keep_cols,
        "extra_feature_cols_used": extra_cols,
        "scaling": scaling.__dict__,
        "cp_prior_params": cp_prior_params,
        "tref": args.tref,
        "n_bits": N_BITS,
        "rho_mean": rho_mean,
        "clean_physics_loss_training": True,
        "density_coupled_cp_prior": False,
        "cp_prediction_form": "Cp_pred = cp_mean + cp_std*NN_output; no ridge Cp-density prior",
        "rho_physics_weight": args.rho_physics_weight,
        "eta_physics_weight": args.eta_physics_weight,
        "cp_const_weight": args.cp_const_weight,
        "loss_definition": "rho/logeta data losses use free predictions; rho/logeta physics losses align free predictions with structured heads; Cp has no density-coupled prior; Cp_const penalizes Cp(T)-Cp(Tref).",
    }, outdir / "insitu_multitask_nn_no_morgan_FULL_clean_physics_loss_training.pt")

    # Compatible checkpoint for existing prediction/screening scripts.
    # It stores the structured base model only.
    torch.save({
        "model_state_dict": model.base_model.state_dict(),
        "degree": args.degree,
        "hidden": parse_hidden(args.hidden),
        "dropout": args.dropout,
        "feature_cols": keep_cols,
        "extra_feature_cols_used": extra_cols,
        "scaling": scaling.__dict__,
        "cp_prior_params": cp_prior_params,
        "tref": args.tref,
        "n_bits": N_BITS,
        "clean_physics_loss_training": True,
        "density_coupled_cp_prior": False,
        "cp_prediction_form": "Cp_pred = cp_mean + cp_std*NN_output; no ridge Cp-density prior",
        "rho_physics_weight": args.rho_physics_weight,
        "eta_physics_weight": args.eta_physics_weight,
        "cp_const_weight": args.cp_const_weight,
        "compatible_checkpoint_note": "Direct/free heads were used only to define clean physics-consistency training; Cp_const was used during training; this checkpoint saves structured base model for existing screening scripts.",
    }, outdir / "insitu_multitask_nn_no_morgan.pt")

    joblib.dump({
        "imputer": imputer,
        "scaler": scaler,
        "feature_cols": keep_cols,
        "cp_prior_pipeline": cp_prior_pipe,
        "cp_prior_params": cp_prior_params,
        "group_to_idx": group_to_idx,
        "idx_to_group": idx_to_group,
        "args": vars(args),
    }, outdir / "preprocessing_and_prior.joblib")

    with open(outdir / "run_summary.json", "w", encoding="utf-8") as f:
        json.dump({
            "input": str(args.input),
            "n_rows": int(len(df)),
            "n_groups": int(point_df["group_id"].nunique()),
            "train_groups": int(len(train_groups)),
            "test_groups": int(len(test_groups)),
            "train_rows": int(len(train_rows)),
            "test_rows": int(len(test_rows)),
            "degree": int(args.degree),
            "n_features": int(X_all.shape[1]),
            "n_bits": int(N_BITS),
            "best_val_loss": float(best_loss),
            "cp_prior_params": cp_prior_params,
            "scaling": scaling.__dict__,
            "clean_physics_loss_training": True,
            "density_coupled_cp_prior": False,
            "cp_prediction_form": "Cp_pred = cp_mean + cp_std*NN_output; no ridge Cp-density prior",
            "rho_physics_weight": float(args.rho_physics_weight),
            "eta_physics_weight": float(args.eta_physics_weight),
            "cp_const_weight": float(args.cp_const_weight),
            "loss_definition": "L = MSE(rho_free,rho_data) + MSE(logeta_free,logeta_data) + MSE(cp_struct,cp_data) + lambda_rho MSE(rho_free,rho_struct) + lambda_eta MSE(logeta_free,logeta_struct) + lambda_cp MSE(Cp_struct(T),Cp_struct(Tref))",
            "checkpoint_note": "insitu_multitask_nn_no_morgan.pt is compatible with existing screening scripts; FULL_clean_physics_loss_training checkpoint includes free/direct heads.",
        }, f, indent=2)

    print(f"\nWrote outputs to: {outdir.resolve()}")


if __name__ == "__main__":
    main()
